### ISSUE TITLE
Train errors on the NuScenes dataset.

### ISSUE THREAD

**Issue by julycrow** [pnnnnnnn/PrevPredMap#2]
When I was training on the NuScenes dataset, the following error occurred. The dataset was prepared according to the ppmap document.

Original Traceback (most recent call last):
  File "/root/anaconda3/envs/ppmap/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/anaconda3/envs/ppmap/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/ppmap/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/disk4/jmk3/Project/PrevPredMap/projects/mmdet3d_plugin/datasets/nuscenes_offlinemap_dataset.py", line 1421, in __getitem__
    data = self.prepare_train_data(idx)
  File "/root/disk4/jmk3/Project/PrevPredMap/projects/mmdet3d_plugin/datasets/nuscenes_offlinemap_dataset.py", line 1185, in prepare_train_data
    input_dict = self.get_data_info(i)
  File "/root/disk4/jmk3/Project/PrevPredMap/projects/mmdet3d_plugin/datasets/nuscenes_offlinemap_dataset.py", line 1370, in get_data_info
    annos = self.get_ann_info(index)
  File "/root/disk4/jmk3/Project/PrevPredMap/mmdetection3d/mmdet3d/datasets/nuscenes_dataset.py", line 271, in get_ann_info
    mask = info['valid_flag']
KeyError: 'valid_flag'

**Comment by pnnnnnnn** [comment]
> When I was training on the NuScenes dataset, the following error occurred. The dataset was prepared according to the ppmap document.
> 
> Original Traceback (most recent call last): File "/root/anaconda3/envs/ppmap/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop data = fetcher.fetch(index) File "/root/anaconda3/envs/ppmap/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/root/anaconda3/envs/ppmap/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/root/disk4/jmk3/Project/PrevPredMap/projects/mmdet3d_plugin/datasets/nuscenes_offlinemap_dataset.py", line 1421, in **getitem** data = self.prepare_train_data(idx) File "/root/disk4/jmk3/Project/PrevPredMap/projects/mmdet3d_plugin/datasets/nuscenes_offlinemap_dataset.py", line 1185, in prepare_train_data input_dict = self.get_data_info(i) File "/root/disk4/jmk3/Project/PrevPredMap/projects/mmdet3d_plugin/datasets/nuscenes_offlinemap_dataset.py", line 1370, in get_data_info annos = self.get_ann_info(index) File "/root/disk4/jmk3/Project/PrevPredMap/mmdetection3d/mmdet3d/datasets/nuscenes_dataset.py", line 271, in get_ann_info mask = info['valid_flag'] KeyError: 'valid_flag'

完成数据准备后，会生成“nuscenes_map_infos_temporal_train.pkl”和“nuscenes_map_infos_temporal_val.pkl”这两个文件。这两个文件每一帧有valid_flag这个信息，理论上不会出现KeyError: 'valid_flag'。或者你可以试试我这边生成的这两个文件（https://drive.google.com/drive/folders/1SIDRaT9H_8JPvR_vaNMiZ3YEtKHUUAdE?usp=sharing）。

**Comment by julycrow** [comment]
感谢您的文件！我仔细核对了custom_nusc_map_converter.py的代码，里面确实没有'valid_flag'相关的代码，或许您还没有更新，期待您的修正。此外，非常感谢您PrevPredMap的工作！

**Comment by pnnnnnnn** [comment]
> 感谢您的文件！我仔细核对了custom_nusc_map_converter.py的代码，里面确实没有'valid_flag'相关的代码，或许您还没有更新，期待您的修正。此外，非常感谢您PrevPredMap的工作！

确实。valid_flag在此代码中没有用处，我注释了需要用到valid_flag的代码，感谢指正！
